### ISSUE TITLE
Crash on Android (Flutter 1.17 + GeniusScanSDK 3.0.19)

### ISSUE THREAD

**Issue by aghanti7** [thegrizzlylabs/geniusscan-sdk-demo#30]
With the latest version of the plugin, seeing the following crash on Android. Works with 3.0.18.

```
07-03 08:15:36.264 15037 15037 E flutter : [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoSuchMethodError: no non-static method "Lcom/thegrizzlylabs/geniusscan/sdk/core/TextLayoutToTextConverter$CppProxy;.<init>(J)V"
07-03 08:15:36.264 15037 15037 E flutter : 	at java.lang.Runtime.nativeLoad(Native Method)
07-03 08:15:36.264 15037 15037 E flutter : 	at java.lang.Runtime.nativeLoad(Runtime.java:1115)
07-03 08:15:36.264 15037 15037 E flutter : 	at java.lang.Runtime.loadLibrary0(Runtime.java:1069)
07-03 08:15:36.264 15037 15037 E flutter : 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
07-03 08:15:36.264 15037 15037 E flutter : 	at java.lang.System.loadLibrary(System.java:1667)
07-03 08:15:36.264 15037 15037 E flutter : 	at com.thegrizzlylabs.geniusscan.sdk.core.GeniusScanLibrary.<clinit>(Unknown Source:9)
07-03 08:15:36.264 15037 15037 E flutter : 	at com.thegrizzlylabs.geniusscan.sdk.core.GeniusScanLibrary.init(Unknown Source:0)
07-03 08:15:36.264 15037 15037 E flutter : 	at com.thegrizzlylabs.geniusscan.sdk.ui.PluginBridge.setLicenseKey(Unknown Source:0)
07-03 08:15:36.264 15037 15037 E flutter : 	at com.thegrizzlylabs.geniusscan.sdk.flutter.FlutterGeniusScanPlugin.onMethodCall(Unknown Source:16)
07-03 08:15:36.264 15037 15037 E flutter : 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
07-03 08:15:36.264 15037 15037 E flutter : 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
07-03 08:15:36.264 15037 15037 E flutter : 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
07-03 08:15:36.264 15037 15037 E flutter : 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-03 08:15:36.264 15037 15037 E flutter : 	at android.os.MessageQueue.next(MessageQueue.java:336)
07-03 08:15:36.264 15037 15037 E flutter : 	at android.os.Looper.loop(Looper.java:174)
07-03 08:15:36.264 15037 15037 E flutter : 	at android.app.ActivityThread.main(ActivityThread.java:7397)
07-03 08:15:36.264 15037 15037 E flutter : 	at java.lang.reflect.Method.invoke(Native Method)
07-03 08:15:36.264 15037 15037 E flutter : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
07-03 08:15:36.264 15037 15037 E flutter : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
07-03 08:15:36.264 15037 15037 E flutter : 
07-03 08:15:36.264 15037 15037 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
07-03 08:15:36.265 15037 15037 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 15037 (m.teakshed.omrx), pid 15037 (m.teakshed.omrx)
07-03 08:15:36.399 15315 15315 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
07-03 08:15:36.400  1018  1018 I /system/bin/tombstoned: received crash request for pid 15037
07-03 08:15:36.401 15315 15315 I crash_dump64: performing dump of process 15037 (target tid = 15037)
07-03 08:15:36.404  2097  2097 D StatusBarMobileView: updateState state.subId = 1  mState.visible:true  state.visible:true  state.typeId:com.android.systemui:drawable/ic_4g_mobiledata  state.strengthId:1283  state.roaming:false  this:StatusBarMobileView(slot=mobile state=MobileIconState(subId=1, strengthId=1283, roaming=false, typeId=2131231277, volteId=2131231608, visible=true))
07-03 08:15:36.410 15315 15315 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-03 08:15:36.410 15315 15315 F DEBUG   : Build fingerprint: 'Xiaomi/laurel_sprout/laurel_sprout:10/QKQ1.190910.002/V11.0.15.0.QFQMIXM:user/release-keys'
07-03 08:15:36.410 15315 15315 F DEBUG   : Revision: '0'
07-03 08:15:36.410 15315 15315 F DEBUG   : ABI: 'arm64'
07-03 08:15:36.410 15315 15315 F DEBUG   : Timestamp: 2020-07-03 08:15:36+0530
07-03 08:15:36.410 15315 15315 F DEBUG   : pid: 15037, tid: 15037, name: m.teakshed.omrx  >>> com.teakshed.omrx <<<
07-03 08:15:36.410 15315 15315 F DEBUG   : uid: 10129
07-03 08:15:36.410 15315 15315 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
07-03 08:15:36.410 15315 15315 F DEBUG   : Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
07-03 08:15:36.410 15315 15315 F DEBUG   : '
07-03 08:15:36.410 15315 15315 F DEBUG   :     x0  0000000000000000  x1  0000000000003abd  x2  0000000000000006  x3  0000007fcd9888e0
07-03 08:15:36.410 15315 15315 F DEBUG   :     x4  0000000000800000  x5  0000000000800000  x6  0000000000800000  x7  0000800000000000
07-03 08:15:36.410 15315 15315 F DEBUG   :     x8  00000000000000f0  x9  7149d5342d27f44c  x10 0000000000000001  x11 0000000000000000
07-03 08:15:36.410 15315 15315 F DEBUG   :     x12 fffffff0fffffbdf  x13 0000000000000003  x14 0000000000000001  x15 0000000000000010
07-03 08:15:36.410 15315 15315 F DEBUG   :     x16 0000007e887648c0  x17 0000007e88740900  x18 0000007e8b940000  x19 0000000000003abd
07-03 08:15:36.410 15315 15315 F DEBUG   :     x20 0000000000003abd  x21 00000000ffffffff  x22 0000000000000020  x23 0000000000000095
07-03 08:15:36.410 15315 15315 F DEBUG   :     x24 0000007d89c7cec0  x25 0000007d89d7a0a0  x26 0000007d99a36000  x27 0000007e8afee650
07-03 08:15:36.410 15315 15315 F DEBUG   :     x28 0000007d99161000  x29 0000007fcd988980
07-03 08:15:36.410 15315 15315 F DEBUG   :     sp  0000007fcd9888c0  lr  0000007e886f20c4  pc  0000007e886f20f0
07-03 08:15:36.526 15315 15315 F DEBUG   : 
07-03 08:15:36.526 15315 15315 F DEBUG   : backtrace:
07-03 08:15:36.526 15315 15315 F DEBUG   :       #00 pc 00000000000830f0  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: cf739dbc84bcc78f7a1500721bfb3758)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #01 pc 00000000002af058  /data/app/com.teakshed.omrx-VemT9SXxCPrPILHze6Qbiw==/lib/arm64/libflutter.so!libflutter.so (offset 0x290000) (BuildId: 9a84530aa21d46fee2c5ee4e6a4b7d1532edfd13)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #02 pc 00000000002a3828  /data/app/com.teakshed.omrx-VemT9SXxCPrPILHze6Qbiw==/lib/arm64/libflutter.so!libflutter.so (offset 0x290000) (BuildId: 9a84530aa21d46fee2c5ee4e6a4b7d1532edfd13)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #03 pc 00000000002a223c  /data/app/com.teakshed.omrx-VemT9SXxCPrPILHze6Qbiw==/lib/arm64/libflutter.so!libflutter.so (offset 0x290000) (BuildId: 9a84530aa21d46fee2c5ee4e6a4b7d1532edfd13)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #04 pc 00000000002dda94  /data/app/com.teakshed.omrx-VemT9SXxCPrPILHze6Qbiw==/lib/arm64/libflutter.so!libflutter.so (offset 0x290000) (BuildId: 9a84530aa21d46fee2c5ee4e6a4b7d1532edfd13)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #05 pc 00000000002b068c  /data/app/com.teakshed.omrx-VemT9SXxCPrPILHze6Qbiw==/lib/arm64/libflutter.so!libflutter.so (offset 0x290000) (BuildId: 9a84530aa21d46fee2c5ee4e6a4b7d1532edfd13)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #06 pc 00000000002b27dc  /data/app/com.teakshed.omrx-VemT9SXxCPrPILHze6Qbiw==/lib/arm64/libflutter.so!libflutter.so (offset 0x290000) (BuildId: 9a84530aa21d46fee2c5ee4e6a4b7d1532edfd13)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #07 pc 000000000001836c  /system/lib64/libutils.so (android::Looper::pollInner(int)+832) (BuildId: 8dcc6a23d7b5c85e8562aa5394a3a42f)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #08 pc 0000000000017f8c  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+56) (BuildId: 8dcc6a23d7b5c85e8562aa5394a3a42f)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #09 pc 000000000013b920  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44) (BuildId: 7c435cb5dc9d1c09ad59f054febe0058)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #10 pc 00000000002a4afc  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+140) (BuildId: 97d0dbc0cdffdee1013d31c09ba87556afe29349)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #11 pc 000000000073ae54  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+228) (BuildId: 97d0dbc0cdffdee1013d31c09ba87556afe29349)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #12 pc 0000000000737c58  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+680) (BuildId: 97d0dbc0cdffdee1013d31c09ba87556afe29349)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #13 pc 00000000004c5894  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+756) (BuildId: 97d0dbc0cdffdee1013d31c09ba87556afe29349)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #14 pc 00000000001365b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 3853a2ceaeb009fc07a0847a55abcf6a)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #15 pc 000000000014500c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: 3853a2ceaeb009fc07a0847a55abcf6a)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #16 pc 00000000004afc18  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: 3853a2ceaeb009fc07a0847a55abcf6a)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #17 pc 00000000004b17bc  /apex/com.android.runtime/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1480) (BuildId: 3853a2ceaeb009fc07a0847a55abcf6a)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #18 pc 000000000043cb60  /apex/com.android.runtime/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: 3853a2ceaeb009fc07a0847a55abcf6a)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #19 pc 00000000000c2c34  /system/framework/arm64/boot.oat (art_jni_trampoline+180) (BuildId: a0b292b21d796006255a63781b8e3067d6a82ca3)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #20 pc 00000000009ae598  /system/framework/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136) (BuildId: 97d0dbc0cdffdee1013d31c09ba87556afe29349)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #21 pc 00000000009b616c  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2076) (BuildId: 97d0dbc0cdffdee1013d31c09ba87556afe29349)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #22 pc 00000000001365b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 3853a2ceaeb009fc07a0847a55abcf6a)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #23 pc 000000000014500c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: 3853a2ceaeb009fc07a0847a55abcf6a)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #24 pc 00000000004afc18  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: 3853a2ceaeb009fc07a0847a55abcf6a)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #25 pc 00000000004af808  /apex/com.android.runtime/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+408) (BuildId: 3853a2ceaeb009fc07a0847a55abcf6a)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #26 pc 00000000003ba5a4  /apex/com.android.runtime/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+624) (BuildId: 3853a2ceaeb009fc07a0847a55abcf6a)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #27 pc 00000000000bf99c  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+116) (BuildId: 7c435cb5dc9d1c09ad59f054febe0058)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #28 pc 00000000000c282c  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+776) (BuildId: 7c435cb5dc9d1c09ad59f054febe0058)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #29 pc 00000000000035b0  /system/bin/app_process64 (main+1376) (BuildId: b37b0ba1daa0a4dfe5092fb9afbc2648)
07-03 08:15:36.527 15315 15315 F DEBUG   :       #30 pc 000000000007e898  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: cf739dbc84bcc78f7a1500721bfb3758)

```

**Comment by guillaume-tgl** [comment]
Do you have this error with our demo app or within your own app?
I've just tried to run our Flutter demo app and it works fine: https://github.com/thegrizzlylabs/geniusscan-sdk-demo/tree/master/flutter-plugin-genius-scan-demo

**Comment by aghanti7** [comment]
@guillaume-tgl thanks for the quick response. This happens in my app; demo app wouldn't try to set license key. The exception is happening only when we call setLicenseKey().

**Comment by guillaume-tgl** [comment]
I've just tried our demo app with a key and it works too. Could you show us how you set the license key and start the SDK?

**Comment by aghanti7** [comment]
```
Future<void> _initGeniusScanSdk() async {
    // this key is fetched from our servers and stored when the app starts
    final _key = <scanSdkKey-from-sharedPrefs>;
    if (_key == null) return false; // error handling is done in the caller

    // set GeniusScan license key - for this upload session
    FlutterGeniusScan.setLicenceKey(_key);
  }
```

The above function is called in initState() in the screen where we have a button to call `FlutterGeniusScan.scanWithConfiguration()`

**Comment by aghanti7** [comment]
A note is that debug build is working, release build is failing. Here are my proguard rules.

```
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep public class io.flutter.embedding.android.FlutterSplashView.$SavedState { *; }
-keep class tvi.webrtc.** { *; }
-keep class com.twilio.video.** { *; }
-keepattributes InnerClasses

```

**Comment by guillaume-tgl** [comment]
Ok, I've been able to reproduce and indeed, it's a Proguard issue. We will fix this in the next version.
In the meantime, you can fix this on your end by ending the following line to your Proguard rules:
`-keep class com.thegrizzlylabs.geniusscan.sdk.** { *; }`
I'm sorry about this issue.

**Comment by aghanti7** [comment]
Thanks @guillaume-tgl

**Comment by guillaume-tgl** [comment]
Fixed in v3.0.20
